alias b := default

default:
    just --justfile {{justfile()}} build

build:
    #!/usr/bin/env bash
    printf "\e[3;33;3m%s\e[0m\n" "Building sudodo"
    go build
    sudo chown root sudo
    sudo chmod u+s sudo

install:
    #!/usr/bin/env bash
    printf "\e[3;33;3m%s\e[0m\n" "Installing sudodo"
    sudo /usr/bin/cp ./sudo /usr/bin

uninstall:
    #!/usr/bin/env bash
    printf "\e[3;33;3m%s\e[0m\n" "Uninstalling sudodo"
    [ -f "/usr/bin/sudo" ] && sudo rm /usr/bin/sudo
    [ -f "$HOME/bin/sudo" ] && rm "$HOME/bin/sudo"
    [ -f "$HOME/.local/bin/sudo" ] && rm "$HOME/.local/bin/sudo"

test-all:
    just --justfile {{justfile()}} build
    just --justfile {{justfile()}} test

test:
    ./sudo cat /etc/shadow

